### ISSUE TITLE
Create a process for moving feature requests from users to engineers

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#107]
@Milstein will be receiving feature requests from users. We need to come up with a process for how we go from user feature requests to engineering those requests. We need to make sure they are 
1. converted into an issue, details, screenshots, and full description
1. approved by Justin or Scott
1. reviewed and updated by engineers
1. original requester confirm this is what they are looking for
1. Issue added to the backlog
1. Issue prioritized

**Comment by joachimweyl** [comment]
Hello @Milstein,
I have taken an initial pass at what the process might look like for feature requests coming from users. Please review.

**Comment by hpdempsey** [comment]
What is described in this issue is the same as the process should be for recording and resolving bugs.  Is there a reason why we need a different process for feature requests?  We might take action on feature requests differently because they are generally not as urgent and involve more people to accomplish, but otherwise the procedure we have of creating an issue, discussing in our call, assigning (or not) and resolving it seems sufficient.  If not, please explain what else is needed.

**Comment by joachimweyl** [comment]
The only difference is that they need to be approved by Justin or Scott. That being said I agree. we can follow the same process we do for resolving bugs and just make sure we get approval from Scott or Justin.
