### ISSUE TITLE
Grant create Role and Rolebinding to Eco Forecasting Collaboratory Project

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#128]
The Ecological Forecasting project called [PEcAn includes several Helm Charts](https://github.com/PecanProject/pecan-helm), including the [RabbitMQ helm chart provided by Bitnami](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq). Unfortunately we are blocked, because as users with only the `edit` role binding in our `software-application-innovation-lab-sail-projects-fcd6dfa` namespace, we are unable to create the [Role](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/templates/role.yaml) and [Role Binding](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/templates/rolebinding.yaml) to run the RabbitMQ Helm Chart. When trying to create these Roles and RoleBindings, we get an error: 

```
roles.rbac.authorization.k8s.io is forbidden: User cannot create resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "software-application-innovation-lab-sail-projects-fcd6dfa"
```

What can we do to create these Roles and Role Bindings within a namespace for RabbitMQ and other applications using roles and role bindings for service accounts?

**Comment by larsks** [comment]
@computate thanks for opening this issue.

As we discussed on slack, I think the temporary solution is to submit some RBAC changes via argocd that allow members of your project to create roles and rolebindings. Unfortunately, that means you're probably going to have to manually maintain a list of project members, since our current coldfront integration directly lists project members in the `edit` rolebinding for the project (rather than creating a group that you could reference in your own rolebindings).

I am working on a proposal to update our coldfront integration to make this easier to manage (and perhaps set up a default RBAC that allows project members to create roles and rolebindings).

**Comment by joachimweyl** [comment]
@computate you mentioned a PR had resolved this. What is the PR and are we ready to close this issue or are there more parts to it?

**Comment by computate** [comment]
@joachimweyl [this "Allow users to create certificate issuers" PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/276) from @larsks partially helped resolve this to allow us to test out routes and certificates in our namespace. We still need to work on some Coldfront integration to allow us to create roles and rolebindings in our namespace as @larsks mentioned.

**Comment by computate** [comment]
Thanks @larsks, this is great for creating and editing Roles. Should users also be able to delete them too with the `delete` verb? I created a test one that I can't delete.

**Comment by larsks** [comment]
@computate it looks like I did indeed forget the `delete` verb in the PR. I'll submit a fix immediately.

**Comment by computate** [comment]
Thanks @larsks , deleting the role works now.
