### ISSUE TITLE
ColdFront mass subscriptions for classes

### ISSUE THREAD

**Issue by hpdempsey** [nerc-project/operations#190]
With at least two classes needing to use RHODs during the fall semester, it would be convenient for profs if they could mass subscribe students.  Need Kristi to weigh in on how hard/easy this is to do and whether it would be possible to add it to production in the near future.  Gagan and Milson are discussing all onboarding for classes that use RHODs on NERC already, so they should be involved in defining the right process if Kristi thinks this is feasible.

**Comment by hpdempsey** [comment]
....and obviously mass unsubscribing would also be desired when classes are done.

**Comment by knikolla** [comment]
There are several things that can be automated here. Depending on the timeline for near future.

- Automating creating projects and resource allocations. This is easy-ish.
- Automating adding already existing users to the above.  Easy.
- Where it gets tricky is the requirement of the users to have already registered with RegApp, as that it the choke point for verifying email addresses and having users approve the EULA. So we can’t automate this point, but we can decouple it from the above to so that when they eventually do, they will already have been granted the required permissions.

**Comment by knikolla** [comment]
https://github.com/nerc-project/coldfront-plugin-api/pull/9 and https://github.com/nerc-project/coldfront-plugin-api/pull/12 implement a standardized REST API (based on SCIM v2) for assigning users to resource allocations in ColdFront. This implements the middle point from my comment above.

With that in place, the new workflow for mass subscriptions is slightly simplified to:
1. PI registers and requests a resource allocation in ColdFront
2. NERC administrators approve the resource allocation
3. Students go through RegApp registration
4. PI gives list of users to add to resource allocation
5. NERC administrators run a command that talks to the API and registers all users.

**Comment by knikolla** [comment]
The API just got rolled out in production yesterday.

Best description of the API to create users and add them to resource allocations can be found in the unit tests since they document the payload.

1. To create a user in ColdFront https://github.com/nerc-project/coldfront-plugin-api/blob/f0bfbd9d5e6707eb8bb7297b782502012d2b1266/src/coldfront_plugin_api/tests/unit/test_users.py#L34-L51
2. Add user to resource allocation https://github.com/nerc-project/coldfront-plugin-api/blob/f0bfbd9d5e6707eb8bb7297b782502012d2b1266/src/coldfront_plugin_api/tests/unit/test_groups.py#L85-L86

**Comment by hpdempsey** [comment]
This is not quite what I'm looking for.  The professors want to submit a list of students who need accounts.  Class size is up to 300.   How do you want that list formatted, and  who is creating accounts from the list.  That is what we want to test.

**Comment by hpdempsey** [comment]
Note that the professors explicitly did not want to tell the students to go through RegAp because they want the students signed up before the first day of class.

**Comment by DanNiESh** [comment]
If I understand the unit test correctly, we could to write a python script similar to these unit tests. 1) generate a csv with student info (name, email), 2) parse the csv to payload format in the unit test, 3) make post requests via coldfront client.

**Comment by knikolla** [comment]
> If I understand the unit test correctly, we could to write a python script similar to these unit tests. 1) generate a csv with student info (name, email), 2) parse the csv to payload format in the unit test, 3) make post requests via coldfront client.

Correct.

**Comment by knikolla** [comment]
> Note that the professors explicitly did not want to tell the students to go through RegAp because they want the students signed up before the first day of class.

At some point students will have to register through RegApp to have access to the services, but that can be after the script performs the registrations into ColdFront. The username that students register in RegApp must match the one in ColdFront though.

**Comment by hpdempsey** [comment]
On Wed, Nov 29, 2023 at 10:35 AM Kristi Nikolla ***@***.***>
wrote:

> If I understand the unit test correctly, we could to write a python script
> similar to these unit tests. 1) generate a csv with student info (name,
> email), 2) parse the csv to payload format in the unit test, 3) make post
> requests via coldfront client.
>
>
Sure, but it is not our job to write that script.  The request is for
Kristi to do this and support it for the ops engineering team.  They need
it before the semester starts in January, and we (or they) need to test it
on a group of students who are using NERC ASAP.

**Comment by DanNiESh** [comment]
I have a list of students (10-ish students) from Orran and Jonathan to test registration. Can you test with that list?

**Comment by knikolla** [comment]
Yes. Are there already approved allocations?

**Comment by knikolla** [comment]
Put 365 in the CSV for `alloacation id`

![Screenshot 2023-12-05 at 4 59 22 PM](https://github.com/nerc-project/operations/assets/4123322/9686bc36-281e-478b-a601-1a6b1da2b96c)

**Comment by knikolla** [comment]
I have processed the CSV that I received from Danni. Users added to allocation.

**Comment by DanNiESh** [comment]
Tested with 10 students from BU. They have all completed registration on their end and have been successfully added to allocation. This issue is resolved.
