### ISSUE TITLE
Allocate 10 nodes from nerc-ocp-prod for hypershift test

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#204]
I'm going to be testing out [Hypershift] and need to allocate a set of 10 nodes; as we've discussed on the call recently, the nodes originally associated with the test cluster are available in the short term for test purposes.

[hypershift]: https://github.com/openshift/hypershift

@jtriley suggested that you're the best person to coordinate node allocation and keep track of which nodes may be unavailable due to hardware issues.

**Comment by aabaris** [comment]
Chassis cmc-9, cmc-10 and the nodes they contain are currently reporting as available, with no hw issues.

I can't promise that they won't report issues once they're put to use, but that's the only way we'd find certain types of problems anyway.

CHASSIS: cmc-9-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-72-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-73-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-74-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-75-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-76-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-77-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-78-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-79-obm.nerc-ocp-prod.rc.fas.harvard.edu

CHASSIS: cmc-10-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-80-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-81-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-82-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-83-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-84-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-85-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-86-obm.nerc-ocp-prod.rc.fas.harvard.edu
wrk-87-obm.nerc-ocp-prod.rc.fas.harvard.edu

**Comment by larsks** [comment]
@aabaris thanks for information.

I'm going to grab nodes wrk-73 - wrk-77 and wrk-83 - wrk-87 for a total of 10 nodes.

@jtriley can you arrange to get these switched over to the test cluster network? Thanks!

**Comment by jtriley** [comment]
Those hosts should be switched over now. We still need to gather mac addresses and configure DHCP for them. I've asked @aabaris to help with this when he gets a moment.

**Comment by aabaris** [comment]
@jtriley  Here are the mac addresses for nodes that Lars picked:

wrk-73-obm.nerc-ocp-prod.rc.fas.harvard.edu,10:7D:1A:9D:F6:6F,10:7D:1A:9D:F6:72
wrk-74-obm.nerc-ocp-prod.rc.fas.harvard.edu,10:7D:1A:9D:F5:E9,10:7D:1A:9D:F5:EC
wrk-75-obm.nerc-ocp-prod.rc.fas.harvard.edu,10:7D:1A:9D:FC:27,10:7D:1A:9D:FC:2A
wrk-76-obm.nerc-ocp-prod.rc.fas.harvard.edu,10:7D:1A:9D:F5:9B,10:7D:1A:9D:F5:9E
wrk-77-obm.nerc-ocp-prod.rc.fas.harvard.edu,10:7D:1A:9D:F7:DD,10:7D:1A:9D:F7:E0
wrk-83-obm.nerc-ocp-prod.rc.fas.harvard.edu,6C:2B:59:88:C7:05,6C:2B:59:88:C7:07
wrk-84-obm.nerc-ocp-prod.rc.fas.harvard.edu,6C:2B:59:8A:F2:21,6C:2B:59:8A:F2:23
wrk-85-obm.nerc-ocp-prod.rc.fas.harvard.edu,50:9A:4C:91:94:95,50:9A:4C:91:94:97
wrk-86-obm.nerc-ocp-prod.rc.fas.harvard.edu,50:9A:4C:91:95:CD,50:9A:4C:91:95:CF
wrk-87-obm.nerc-ocp-prod.rc.fas.harvard.edu,50:9A:4C:91:92:A9,50:9A:4C:91:92:AB

Information for all FX nodes can be found here (provided by Hakan I believe):
https://github.com/OCP-on-NERC/docs/blob/663b1bb29c0298656890ecb773afd60ce8adf7ef/architecture/hardware.csv
I did check CMCs directly in case something changed since this document was update and found information to be consistent.

**Comment by larsks** [comment]
Thanks, I think we're all set as far as this issue is concerned.

**Comment by jtriley** [comment]
Just a note that we ended up using `wrk-[72-79,83,84]` for hypershift testing.
