### ISSUE TITLE
Allocate addresses and hostnames (api, ingress) for hypershift cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#213]

**Comment by larsks** [comment]
@jtriley @aabaris I need to reserve some vip addresses on the test network for use as vip. I'm not sure how you folks handle IPAM.

I need a total of six addresses.

**Comment by aabaris** [comment]
So I am not clear on how to track this and I have to ask @jtriley to review and provide some guidance.

the "baremetal TEST" network is 10.30.8.0/24.  
dhcp-range=set:vlan2174,10.30.8.3,10.30.8.254,255.255.255.0
My understanding is that no IPs from this range are handed out by DHCP server without explicit MAC address mapping, and therefore we don't necessarily need to change the configured range when allocating IPs for use outside of DHCP?  Currently only 10.30.8.7-22  have been mapped to hosts in DHCP config.

I could propose that we allocate:
10.30.8.249 - 10.30.8.254

I would appreciate some confirmation that I'm providing the right allocation and guidance on how we should track it.  I suspect Netbox could become the source of this truth eventually.  I have not been able to find an existing way to represent this in either our github or gitlab repos.

Also, I noticed that dhcp has been configured to assign the nodes allocated for hypershift to the PROD baremetal network 10.30.6.0/23 rather than test.  Is that right?

Augustine

**Comment by larsks** [comment]
> Also, I noticed that dhcp has been configured to assign the nodes allocated for hypershift to the PROD baremetal network 10.30.6.0/23 rather than test. Is that right?

No, these need to be deployed on the test network. I think I have the necessary permissions so set that up, although I may need a reminder exactly where that happens. I will follow up on slack.

> I suspect Netbox could become the source of this truth eventually.

:+1:

**Comment by larsks** [comment]
From @jtriley in slack:

> Virtual IPs are defined in DNS - they’re not DHCP'd. That said we just need to pick some IPs. I would suggest 10.30.8.80 for the API and 10.30.8.81 for the Ingress/loadbalancer. I'm updating DHCP now to switch these nodes to the test nets.

**Comment by aabaris** [comment]
@jtriley it looks to me that we only provided 2 ip address out of 6 requested.

My recollection is that you suggested 90,91,100,101 in conversation?   I would like to follow up on this, so I am in a better position to help people in the future, 

but in the mean time, are we ok giving Lars:
10.30.8.80
10.30.8.81
10.30.8.90
10.30.8.91
10.30.8.100
10.30.8.101
?

**Comment by jtriley** [comment]
@aabaris yes those addresses should be fine and well outside the range of currently used addresses by the `nerc-ocp-test` cluster.

**Comment by larsks** [comment]
The initial cluster is hypershift1.int.massopen.cloud:

- https://api.hypershift1.int.massopen.cloud
- https://console.apps.hypershift1.int.massopen.cloud
