### ISSUE TITLE
Create a new test realm in the NERC Keycloak for OPE end-to-end tests

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#274]
Refer to #259 
We would like to create ope end-to-end tests with users who come in from ColdFront. The steps are suggested by Kristi:

- Create a new test realm in the NERC Keycloak
- Integrate this new realm into the already existing ColdFront staging environment, setting up authentication through it. As we have already integrated this with the production realm it's only a matter of switching the URL and some parameters.
- Integrate this realm as a new alternative log in option for the NERC OCP, so that users in this test realm are able to authenticate to OCP. As we have already integrated the production realm, it's only a matter of duplicating the config entry and shifting some parameters.
- Use the Keycloak REST API to create the desired number of test users in this new realm. These users will then show up in the ColdFront staging web interface when a PI searches for users to add to a resource allocation and will be able to log in to OCP.
- Set up the desired test scenario by creating resource allocations and assigning users to these projects. Kristi can help writing simple scripts to facilitate this.

**Comment by joachimweyl** [comment]
@dystewart please break this into smaller issues.

**Comment by dystewart** [comment]
Separating into tasks..

- [ ] Create a new test realm in the NERC Keycloak - Dylan
- [ ] Integrate this new realm into the already existing ColdFront staging environment, setting up authentication through it. As we have already integrated this with the production realm it's only a matter of switching the URL and some parameters. - Dylan
- [ ] Integrate this new realm into the already existing ColdFront staging environment, setting up authentication through it. As we have already integrated this with the production realm it's only a matter of switching the URL and some parameters. - Dylan
- [ ] Use the Keycloak REST API to create the desired number of test users in this new realm. These users will then show up in the ColdFront staging web interface when a PI searches for users to add to a resource allocation and will be able to log in to OCP. - Dylan
- [ ] et up the desired test scenario by creating resource allocations and assigning users to these projects. Kristi can help writing simple scripts to facilitate this.- Kristi

**Comment by joachimweyl** [comment]
@dystewart my worry with having this many issues in one place is that the comments and discussions will get convoluted by trying to discuss so many different things in one issue. If you have some way you plan to alleviate that issue ignore this comment. Otherwise, I would suggest breaking this down.

**Comment by dystewart** [comment]
This issue is actually outdated, we have opted against creating a new Keykloak realm to integrate with the ColdFront staging environment. We have some students from Orran's class which we will have log into a testing namespace instead. 
I need to create a new issue for this. 
As for scale testing @DanNiESh has opened another issue:https://github.com/nerc-project/operations/issues/319
