### ISSUE TITLE
Configure prod rhods for ope courses  (Jan 18 ope course start date)

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#361]
For Orran's course that will be utilizing rhods we will need to stand up a new OCP cluster for the Spring semester. Our prod rhods does provide the user experience that ope are looking for due to the configuration of the rhods install in prod. See this slack [thread](https://massopencloud.slack.com/archives/C027TDE52TZ/p1704401866456499) for more specifics.

For more info on motivations behind doing this see this thread I've opened in the rhods redhat slack: [thread](https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1704397246338279)

In short, this will greatly simplify the student experience for this course since we can curate the rhods install to the needs of the students, which is something we cannot do in the current prod install on a namespace basis. 

To be clear this will not eliminate the ability for students to see each other's notebooks and log into them, though that level of security is possible by creating and granting access to a datascience project per student (which is not really feasible with the number of student we will be hosting). This however does grant us the ability to allow student to launch their notebooks through the jupyter tile in rhods, without seeing/clicking through and other notebooks in the process.

The first step here is to find some hardware and get OCP installed there ASAP since this course will be going like Jan. 18

**Comment by msdisme** [comment]
From a discussion with @hakasapl I think the hardware is available.  

Can you say more about how we plan to configure it and the expected number of nodes?

**Comment by dystewart** [comment]
@msdisme As far as configuration, we will be able to mirror much of what we've done with the test cluster, minus a few unnecessary operators. The big difference is that we will need to set up networking so that the cluster is available externally, much like prod.  

We will also need Ceph set up for this cluster as well, since the notebooks all require a pvc

As for number of nodes, since this cluster is just for OCP/rhods:
- 3-4 control plane nodes (minimum required by OCP is 3)
- 10-20 worker nodes (not exactly sure here depends on the hosts)

This course will have 300 or more students, and we have to be prepared for all students logging in and spinning up notebooks concurrently.

**Comment by dystewart** [comment]
Dropping the prob rebuild doc here since much of the process will look the same: [https://github.com/nerc-project/nerc-runbooks/blob/main/docs/nerc-ocp-prod-rebuild.md](https://github.com/nerc-project/nerc-runbooks/blob/main/docs/nerc-ocp-prod-rebuild.md)

**Comment by joachimweyl** [comment]
@hakasapl what hardware would you suggest for this?
@dystewart will you be standing this cluster up?

**Comment by msdisme** [comment]
Some notes from a discussion with Heidi:
1. authentication via NERC coldfront.
	a. think it needs to be
2. how do we gather info/etc. for billing purposes
	a. do we treat as su's or bare metal?  
		what we decide here is secondary since for this semester they are being charged a flat fee per student, but goal was to begin figuring out what it would be if part of regular cluster
3.  who's monitoring/managing- NERC, Gerard/CS, some group of us?
	a. hook in the same way prod and dev do?
4. use NERC OpenShift as the base line?
	a. yes pease
5. Separate NESE storage requirement?
	a. can we share the ones being used for OPE dev cluster or do we need a new one?

**Comment by joachimweyl** [comment]
@naved001 since racks 1&2 have been added to ESI are we able to provide @dystewart access to the nodes he needs via ESI? If so can we start by offering him 3 FC430s and 5 FC830s?

**Comment by naved001** [comment]
I have allocated the following nodes to the ESI project `orran_cloud_computing`:

FC430:
MOC-R4PAC24U31-S1A
MOC-R4PAC24U37-S3C
MOC-R4PAC22U31-S1A

FC830:
MOC-R4PAC24U05-S3
MOC-R4PAC24U03-S1
MOC-R4PAC24U03-S3
MOC-R4PAC22U27-S1
MOC-R4PAC22U25-S1

**Comment by joachimweyl** [comment]
@dystewart please confirm you are able to access the allocated hardware.

**Comment by msdisme** [comment]
From Orran email:

I just spoke to Erwan, and it appears like there is a straightforward path forward.
 
So the issue for classes is that the project concept gives all users in a project access to all of the containers of all the other users in that project.
 
There is a default project, I think he said jupyter something, where if you use the tile (see below), rather than the project interface, users containers are spun up isolated from each other in that project.    What we can do is readily turn off the project functionality for any user in a class, and if they use the tile to spin up containers, everything will work like it always did on AWS.
![image](https://github.com/nerc-project/operations/assets/6126065/988b4e48-d427-477e-93a9-efc4fb00bfd2)
 
Turns out, that for NERC, the “launch application” link is missing if you look below.  We must have done something special to turn that off.  So, we also have to re-enable “launch application” on the NERC tile for RHODS.
![image](https://github.com/nerc-project/operations/assets/6126065/37b0f091-1494-44ac-9211-99e220eab147)

Description automatically generated
 
 
Research users would still use the normal project interface.  Classes would use the tile feature.  The PODs created will have the user name in them, so we would eventually need to map back from a user to a course; but that is secondary for the short term.
 
So, we need to do two things:
Re-enable launching a notebook from the tile directly.
Disable for all course students access to the projects interface.
 
I think we can/should discuss proper multi-tenancy support in RHODS longer term, but, as far as I can tell, this immediately solves our problems with the classes for at least the near term.  It would be nice to have per-class resource management controls…. But we can worry about that later.

**Comment by joachimweyl** [comment]
@dystewart please review the notes above.

**Comment by dystewart** [comment]
Enables rhods notebook controller: [https://github.com/OCP-on-NERC/nerc-ocp-config/pull/338](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/338)

**Comment by dystewart** [comment]
Update default jupyter notebook pvc size in rhods-notebooks: [https://github.com/OCP-on-NERC/nerc-ocp-config/pull/339](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/339)

**Comment by joachimweyl** [comment]
We will leave these nodes available for now and if we get a new project we need them for we can open a new issue.
