### ISSUE TITLE
Upgrade nerc-admin01 to meet dependencies of OSP 17 upgrade

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#365]
In order to upgrade OpenStack to version 17, VMs running on nerc-admin01 will need to be converted form i440 to q35 chipset in order to support upgrade to RHEL9.

To perform this update we need to:
1) determine strategy for backing up existing system
2) decide upgrade vs clean re-install
3) agree on target OS, currently planning RHEL9
4) decide what hardware to use:
   a) existing R430
   b) decommission R430 from overcloud and migrate to that
   c) install additional disk to existing R430 in order to have a easy back-out plan
5) downtime
   a) DHCP outtage? or migrate to backup HW
   b) When?

**Comment by StHeck** [comment]
We must first convert nerc-admin01 from CentOS 7 to RHEL 7:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/converting_from_an_rpm-based_linux_distribution_to_rhel/index

**Comment by StHeck** [comment]
Then, we must upgrade it from RHEL 7.9 to RHEL 8.8:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/upgrading_from_rhel_7_to_rhel_8/index

**Comment by StHeck** [comment]
Before upgrading nerc-admin01 from RHEL 8.8 to RHEL 9.2, we must modify the VM machines:

Change FW type from pc-i440fx-rhel7.0.0 to pc-i440fx-rhel7.6.0 in all VMs so they will boot when host goes to 9.2.
[root@nerc-admin01 ~]# virsh edit <vm-name>
From:
    \<type arch='x86_64' machine='pc-i440fx-rhel7.0.0'>hvm</type\>
To:
    \<type arch='x86_64' machine='pc-i440fx-rhel7.6.0'>hvm</type\>
We can move them to q35 later. It's a little more involved.

Since Red Hat removed support for QXL and SPICE in their virtualization packages due to a H.264 codec licensing issue,
it would be easier to change the graphics here using virt-manager then before upgrading to 9.2.
Here is their fix using virsh edit: https://access.redhat.com/solutions/6955095

**Comment by StHeck** [comment]
This is my plan of action:

[centos7.9-to-rhel9.2.txt](https://github.com/nerc-project/operations/files/14103674/centos7.9-to-rhel9.2.txt)

**Comment by StHeck** [comment]
nerc-admin01 is now running RHEL9.2.
