### ISSUE TITLE
Professors and TA's for CS210 Spring  2024

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#373]
This will have an attached CSV for adding the professors and ta's.

**Comment by msdisme** [comment]
[CS210_course_staff.csv](https://github.com/nerc-project/operations/files/13907566/CS210_course_staff.csv)

**Comment by msdisme** [comment]
@knikolla please close when done (sorry if already done.)

**Comment by knikolla** [comment]
Done.

The automated process failed on two of the users from the list which I had to process manually due to a bug in `coldfront-plugin-api`. I already proposed a [fix](https://github.com/nerc-project/coldfront-plugin-api/pull/23) for it, but that won't be live in time for the classes and that's totally fine since I'd rather spend the 10 minutes to process the strugglers manually through the ColdFront UI.
