### ISSUE TITLE
Invalid certificates on infra console and applications

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#382]
The new wildcard certificate `*.apps.nerc-ocp-infra.rc.fas.harvard.edu` from Mon, 15 Jan 2024 07:17:29 GMT to Wed, 14 Jan 2026 07:17:30 GMT for the infra cluster is invalid. It's preventing the console and dex authentication from working, and other apps like ArgoCD and Vault from working as well.

**Comment by larsks** [comment]
I think @jtriley will need to issue a new certificate.
 
I would like to raise the priority of https://github.com/nerc-project/operations/issues/214, which would allow us to use automatically generated certificates from Lets Encrypt rather than relying on manually issued certificates from InCommon.

**Comment by larsks** [comment]
> does this maybe belong together?

I suspect that is related, yes.

**Comment by dystewart** [comment]
Sounds like this is probably the cause of: [372](https://github.com/nerc-project/operations/issues/372) as well

**Comment by joachimweyl** [comment]
@jtriley ^

**Comment by jtriley** [comment]
I've updated the certs in vault for both ingress and API server and confirmed the secrets in `openshift-config` (API) and `openshift-ingress` (Ingress) match what's in vault.

**Comment by jtriley** [comment]
This seems to have been caused by incorrect manifests being applied on the infra cluster that were meant for the new OBS cluster (see https://github.com/nerc-project/operations/issues/388). After updating the `IngressController` and `APIServer` resources to match what's defined in the `nerc-ocp-config` repo for the `nerc-ocp-infra` overlay, the new InCommon certs are now active and valid.

Most likely this was caused due to those incorrect manifests given that they did not specify a cert which means they would get auto-generated, self-signed ones from kubernetes (via the default ingress and API cert issuers) as we observed in this case. Additionally the specs for those resources referenced the `nerc-ocp-obs` DNS which would also cause issues on the infra cluster. In any case we now have new InCommon certs.
