### ISSUE TITLE
NERC Core Network Upgrade Discussion

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#390]
## Motivation
What are the next steps for the NERC Core Network?

## Completion Criteria
We have enough information to kick of a meeting with Nick to discuss next steps for upgrading the NERC core network

## Questions
- What switches are we looking to replace?
   - With what new switches?
- How will this affect ESI node interactions?

## Description
- [x] @hakasapl provide diagram link
- [x] @hakasapl add questions or answers to questions above
- [x] @syockel add questions or answers to questions above
- [x] Gather more details
- [x] @joachimweyl create a meeting with key players (Hakan, Justin, Wayne, Nick, Scott, etc)

## Links
- [9/15/2023 Meeting notes](https://docs.google.com/document/d/1t0JyAKus11PgnpoV7WDMkHnS0qFWjnnjBW5eqAW84tE/edit#heading=h.6nb0xe3qdt3z)
- [01/18/2024 Meeting Notes](https://docs.google.com/document/d/1vsjV13mljGiw-6EKtfF4W3AKTPKivnx1gUFI1adLI_0/edit)
- Network diagram

## Completion dates
Desired - 2024-01-29
Required - TBD

**Comment by hakasapl** [comment]
MOC Network Diagrams:

## Data Plane

[MOCA Network Diagrams - MOC-DataPlane-1.pdf](https://github.com/nerc-project/operations/files/14042312/MOCA.Network.Diagrams.-.MOC-DataPlane-1.pdf)

## Management Plane

[MOCA Network Diagrams - MOC-MgmtPlane-1.pdf](https://github.com/nerc-project/operations/files/14042314/MOCA.Network.Diagrams.-.MOC-MgmtPlane-1.pdf)

**Comment by hakasapl** [comment]
Do we actually need to replace switches? Or is the goal to buy new NERC core switches, and use the existing harvard-controlled top of rack switches, but change how they are managed to NERC management instead of harvard?

On the ESI side once a new NERC core exists, we probably want to run a new 2x100G link out to a NERC core switch (current NERC vlans are coming into the ESI network via a Harvard link).

**Comment by hakasapl** [comment]
Notes from NERC meeting: We just need to buy new core switches - these should probably be Cisco if they are under harvard management. I defer to Nick about what they should be.

We should then setup a new link to MOC core network from these switches after they are deployed

**Comment by joachimweyl** [comment]
@hakasapl have you heard back from Nick about what type of switches these should be?

**Comment by hakasapl** [comment]
I believe Chuck from BU is handling the purchasing of the core switches, ongoing email thread

**Comment by joachimweyl** [comment]
@hakasapl have you had any updates from Chuck? What are next steps?

**Comment by hakasapl** [comment]
I think we're still in the purchasing phase. @msdisme any updates?

**Comment by joachimweyl** [comment]
@msdisme any update on the quote?

**Comment by joachimweyl** [comment]
@hakasapl please update the issue with notes from the meeting.

**Comment by hakasapl** [comment]
After a couple discussions w/ Nick:

1. MOC (and therefore ESI) will control all NERC switches (all L2)
2. NERC switches will no longer be managed directly by Harvard, but Harvard can have visibility and management into the switch configurations via [ansible-switches](https://github.com/CCI-MOC/ansible-switches)
3. Harvard will continue to manage anything L3, including routing and firewalls, so the MOC will only deal with L2
4. 2x NERC core switches will be purchased and installed in R6-PB-C02. These switches will uplink to Harvard, then all the existing fiber for NERC TORS switches (2 racks), will need to be re-ran to these switches.
    * It's possible we can do this without downtime since there are 2 TORS per rack in redundant config
5. MOC will need to write or revise Cisco NXOS drivers for ESI
6. MOC will need to write Cisco NXOS driver for ansible-switches (this is more important because ESI will come later)
7. MOC will switch to MSTP and define NERC VLANs in MST 0 to play nice with Harvard's MSTP
    * After this is done, a link can be made between NERC core and Harvard core that does not cause a loop with the existing link from MOC core > Harvard core
8. @msdisme coordinate buying 2x Cisco 9336C w/ L3 license for NERC core

I will make this into an epic sometime this week

**Comment by joachimweyl** [comment]
@hakasapl it sounds like the Discussion part is done, shall we close this issue and create action issues to do the work?
