### ISSUE TITLE
Integrate gradescope autograder into prod cluster

### ISSUE THREAD

**Issue by IsaiahStapleton** [nerc-project/operations#434]
Orran has a student working on a [gradescope autograder](https://github.com/rkulskis/gradescope-autograder) for his EC 440 class. This autograder will be running as a container that the students can send their work to in order to be graded and receive a file back with the results of the autograder. This container image for the autograder will contain tests that Orran doesn't want the students to see, so it needs to be private, ie not accessible to the students. They would like to do this using [OpenShift's internal registry](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.1/html/registry/architecture-component-imageregistry). This registry in prod NERC isn't exposed publicly. So we need to figure out a way to allow them to publish images to this registry.

I am sure Orran would also be open to alternatives solutions to this problem as well. Lars mentioned it would be possible to store the data outside the image in something such as a PV and then mount it to the container at runtime. I think Orran just wants the easiest solution which right now would be to publish the container image with the data included in the image to prod NERC image registry so students can't see the data contained within the image.

**Comment by larsks** [comment]
I spoke with @okrieg about this a bit this evening.

My understanding is that the goal here is to run a service that receives a student submission from gradescope, runs some tests on the student artifacts, and then returns a result to gradescope. The goal is to keep the tests secret.

Rather than embedding the tests in an image and making use of a private registry, I'd like to propose an alternate solution that I believe (a) doesn't require much, if any, additional work and (b) is ultimately much more flexible:

Instead of embedding the tests directly in the image, fetch the tests from a private Git repository. This has a number of advantages:

1. The image itself can be public and can be hosted on your favorite public image registry (docker hub, ghcr.io, quay.io, etc).

2. The image doesn't need to be rebuilt when the tests change; it can be used for multiple assignments and multiple classes.

3. The tests live in a version controlled repository with all the advantages that brings for change control, shared development, etc.

This may not require **any** code changes to the existing solution. Instead of embedding the tests in the image:

- Add an [initContainer](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) to the service deployment that fetches the git repository into a local volume. The container would get credentials for accessing the private git repository from a [Secret](https://kubernetes.io/docs/concepts/configuration/secret/).

- Configure the service container to mount the same volume into the location in which the service expects to find the tests.

This solution doesn't require any cluster-wide changes and, because it decouples the tests themselves from the image that runs the tests, it provides options for re-use that aren't available when embedding tests directly in the image.

---

That said, if necessary we can [enable the public endpoint for the image registry](https://docs.openshift.com/container-platform/4.14/registry/configuring-registry-operator.html#registry-operator-default-crd_configuring-registry-operator); that will require a pull request to https://github.com/OCP-on-NERC/nerc-ocp-config.

Based on the documentation for [accessing the registry](https://docs.openshift.com/container-platform/4.14/registry/accessing-the-registry.html) we will probably need to make some RBAC changes as well.

**Comment by larsks** [comment]
I've put together a sample repository that demonstrates briefly what this might look like:

- https://github.com/larsks/example-test-runner

I've commented up the [deployment manifest](https://github.com/larsks/example-test-runner/blob/main/manifests/deployment.yaml), which is where most of this logic is implemented. There's a dummy Python app in the repository just to show how things might be consumed, but it doesn't really do anything.

**Comment by larsks** [comment]
You could also push your images to an external private registry, and add [pull secret](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) in OpenShift so that your deployment can access the private image.

I saw some references to quay.io in slack, but note that GitHub also has a container registry and it's very easy to add a custom workflow to your project that will build an image and push it to the registry automatically.

**Comment by IsaiahStapleton** [comment]
I discussed this with the student Ross that is going to be working on this. We decided on going with the first suggestion from Lars: pushing the image to a public registry without the tests embedded in the issue, then having the tests in a private GH repo, and using an initContainer that fetches the private git repo. When Ross has the solution ready I will link it to this issue so that there can be a code review.

**Comment by IsaiahStapleton** [comment]
Ross has deployed the solution to prod cluster and decided to include the tests within the image for now since he wanted a quick solution. He said he will be working on adapting the solution to match what we discussed above this week. After he is done he will make a PR to one of the NERC repos either [nerc-ocp-config](https://github.com/OCP-on-NERC/nerc-ocp-config) or [nerc-ocp-apps](https://github.com/OCP-on-NERC/nerc-ocp-apps).

**Comment by joachimweyl** [comment]
@IsaiahStapleton based on your last comment it sounds like there is nothing left for you to do and Ross will manage the rest. Can this issue be closed?

**Comment by IsaiahStapleton** [comment]
@joachimweyl Yes. I have formatted his solution so that I can create a PR to nerc-ocp-apps. I was waiting to solve this issue we were having before making the PR but it has just been solved. I will make the PR today and then that should close this issue.
