### ISSUE TITLE
Gather RHODS feedback from Teachers and TA's

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#502]
## Motivation
Grow RHODS into the product we need it to be.

## Completion Criteria
Feedback gathered from at least 1 TA. It would be nice if we could get feedback from every Teacher and TA but the reality is it can be hard to get Teachers and sometimes even TAs to respond.

## Description
- [x] Create a questionnaire for Teachers and TAs who used RHODS
- [x] Create a questionnaire for students
- [x] Gather responces
- [x] Provide feedback to RHODS team

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by IsaiahStapleton** [comment]
I have created a rough draft of the questionnaire but the intended audience was for the students, linked [here](https://forms.gle/PTQNwaYGqbJfPMTV7). I can either reformat it so that teachers and TAs can also fill it out or create a separate one for them. I plan on talking to Orran today to ask him to give the students a dedicated 10 minutes at the beginning of class so that they can all provide feedback.

**Comment by IsaiahStapleton** [comment]
I've created the two questionnaires for both students and professors. I've sent them to Michael so he can send them out to the students and professors. Once that is done we have to wait to receive responses.
