### ISSUE TITLE
Delegate nerc.mghpcc.org to nerc route53 nameservers

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#620]
Delegate the `nerc.mghpcc.org` domain to route53 domain(s) managed by the NERC so that the `nerc-dns` repository can populate new records in `nerc.mghpcc.org`.

**Comment by jtriley** [comment]
I currently have a ticket submitted to elevate my privileges to manage IAM users in our "prod" AWS account. In the meantime, @culbert is adding the DNS records mentioned here by hand: https://github.com/nerc-project/operations/issues/619 although with the following changes given that having NERC in the name isn't really necessary given the subdomain:

```
api.ocp-test-2 128.31.20.90
api-int.ocp-test-2 192.168.50.250
*.apps.ocp-test-2 128.31.20.112
```

He's also getting me the current zonefile for nerc.mghpcc.org and the policy attached to the route53 user we use to manage letsencrypt. We plan to meet later this week when the ticket I have open gets addressed and set up proper delegation for the nerc.mghpcc.org subdomain.

We will also, at that time, update the `{keycloak, regapp, coldfront}.mss.mghpcc.org` A records in MGHPCC's route53 instance to be CNAME's to `{keycloak, regapp, coldfront}.nerc.mghpcc.org` so that those names persist but the addresses live in the delegated zone.

**Comment by tssala23** [comment]
Thank you very much @jtriley and @culbert. Will close #619 now

**Comment by joachimweyl** [comment]
@jtriley what is the next step for this?

**Comment by jtriley** [comment]
We were able to delegate nerc.mghpcc.org yesterday. This is now managed by the nerc-dns repo.
