### ISSUE TITLE
Query about autopilot from ec528 course

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#795]
@naved001 and @computate, @anish701 asks if there is any route exposed for the Autopilot service or the Kubernetes API (see https://github.com/IBM/autopilot?tab=readme-ov-file#manually-query-the-autopilot-service). The service account doesn't have access to view existing routes, so I just wanted to check if there are any available endpoints that our app can connect to run Autopilot health checks or view nodes (through the Kubernetes API).

**Comment by computate** [comment]
Hi @msdisme and @Anish701 , the autopilot Service for our Prod cluster is actually available at this internal service URL `autopilot-healthchecks.autopilot.svc:3333`. See if it works for you: 

```bash
$ oc debug
$ curl http://autopilot-healthchecks.autopilot.svc:3333/status?check=dcgm&r=2
```

**Comment by Anish701** [comment]
Hi @computate, thank you! The commands work on my end. 

Although the autopilot service endpoint and the default Kubernetes endpoint (https://kubernetes.default.svc) are both accessible in the debug pod, neither can be resolved by our front-end application. I believe this is because our application is not running on the same cluster, so it does not have access to the internal service URLs.

Would it be possible to deploy our application on the Prod cluster (the same cluster running the Autopilot service)? Let us know the best way we can go about this.

Here is the link to the latest container image of our app: quay.io/anish2sinha/autopilot-dashboard:autopilot-dashboard
Here is the topology for the project where our app is currently deployed: https://console.apps.shift.nerc.mghpcc.org/topology/ns/autopilot-dashboard-f3dc9e?view=graph
